/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWorkspaceIdIndexRouteImport } from './routes/w.$workspaceId.index'
import { Route as WWorkspaceIdUploadRouteImport } from './routes/w.$workspaceId.upload'
import { Route as WWorkspaceIdSettingsRouteImport } from './routes/w.$workspaceId.settings'
import { Route as WWorkspaceIdDayDateRouteImport } from './routes/w.$workspaceId.day.$date'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexRouteImport.update({
  id: '/w/$workspaceId/',
  path: '/w/$workspaceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdUploadRoute = WWorkspaceIdUploadRouteImport.update({
  id: '/w/$workspaceId/upload',
  path: '/w/$workspaceId/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdSettingsRoute = WWorkspaceIdSettingsRouteImport.update({
  id: '/w/$workspaceId/settings',
  path: '/w/$workspaceId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdDayDateRoute = WWorkspaceIdDayDateRouteImport.update({
  id: '/w/$workspaceId/day/$date',
  path: '/w/$workspaceId/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsRoute
  '/w/$workspaceId/upload': typeof WWorkspaceIdUploadRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/day/$date': typeof WWorkspaceIdDayDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsRoute
  '/w/$workspaceId/upload': typeof WWorkspaceIdUploadRoute
  '/w/$workspaceId': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/day/$date': typeof WWorkspaceIdDayDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsRoute
  '/w/$workspaceId/upload': typeof WWorkspaceIdUploadRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/day/$date': typeof WWorkspaceIdDayDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/upload'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/day/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/upload'
    | '/w/$workspaceId'
    | '/w/$workspaceId/day/$date'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/upload'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/day/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  WWorkspaceIdSettingsRoute: typeof WWorkspaceIdSettingsRoute
  WWorkspaceIdUploadRoute: typeof WWorkspaceIdUploadRoute
  WWorkspaceIdIndexRoute: typeof WWorkspaceIdIndexRoute
  WWorkspaceIdDayDateRoute: typeof WWorkspaceIdDayDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/': {
      id: '/w/$workspaceId/'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof WWorkspaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/upload': {
      id: '/w/$workspaceId/upload'
      path: '/w/$workspaceId/upload'
      fullPath: '/w/$workspaceId/upload'
      preLoaderRoute: typeof WWorkspaceIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/settings': {
      id: '/w/$workspaceId/settings'
      path: '/w/$workspaceId/settings'
      fullPath: '/w/$workspaceId/settings'
      preLoaderRoute: typeof WWorkspaceIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/day/$date': {
      id: '/w/$workspaceId/day/$date'
      path: '/w/$workspaceId/day/$date'
      fullPath: '/w/$workspaceId/day/$date'
      preLoaderRoute: typeof WWorkspaceIdDayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  WWorkspaceIdSettingsRoute: WWorkspaceIdSettingsRoute,
  WWorkspaceIdUploadRoute: WWorkspaceIdUploadRoute,
  WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
  WWorkspaceIdDayDateRoute: WWorkspaceIdDayDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
